name: controle_arduino
description: "A new Flutter project."

# Impede a publicação acidental para o pub.dev
publish_to: 'none' # Remova essa linha se desejar publicar no pub.dev

# Define a versão do seu aplicativo
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Dependência para ícones do Cupertino (iOS)
  cupertino_icons: ^1.0.8

  # Bibliotecas adicionais para comunicação serial e manipulação de arquivos JSON
  flutter_libserialport: ^0.4.0
  path_provider: ^2.0.11
  json_annotation: ^4.4.0
  file_picker: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting para boas práticas de codificação
  flutter_lints: ^5.0.0

flutter:

  # Garante que o ícone Material seja incluído
  uses-material-design: true

  # Se for utilizar assets, descomente e adicione as linhas abaixo:
  # assets:
  #   - assets/exemplo_comando.json

  # Se for usar fontes personalizadas, configure conforme necessário
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
